### ISSUE TITLE
Work with chartkick

### ISSUE THREAD

**Issue by randy-girard** [codesnik/calculate-all#1]
This is great gem especially when combined with groupdate. Is there anyway to get it to format multie aggregates when used with groupdate so that it will work with chartkick?

**Comment by codesnik** [comment]
wow, I somehow missed that issue completely! Did it work for you, after all?

**Comment by codesnik** [comment]
Actually, I built this gem to use with chartkick. I don't remember all the details of it working with multiple aggregates, but I certain I did it. If you had some trouble and later resolved it, I'd really appreciate if you could help to improve documentation in that area.
