### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by vasilakisfil** [codesnik/calculate-all#2]
Have you checked it against Rails 5? After running the following:

```ruby
Feed.all.calculate_all(:visits_count)
```
I get: 
```ruby
fatal: exception reentered
from /home/vasilakisfil/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
```

Feed is a relatively simple model.

**Comment by codesnik** [comment]
@vasilakisfil Sorry, I missed the issue.
gem should be working with rails5, thanks to @StefSchenkelaars 
But your exception message seem quite weird.
can you please check again with 0.2.0 version of the gem?
