### ISSUE TITLE
Changes groupdate's format

### ISSUE THREAD

**Issue by haffla** [codesnik/calculate-all#6]
Hi and thanks for this great gem.

There is one issue I am seeing when used together with `groupdate`. The resulting hash's keys are always DateTimes (e.g. `2018-01-03 00:00:00 UTC`) no matter `format` parameter is given to `groupdate`. See https://github.com/ankane/groupdate#keys. It seems that the format is overwritten somewhere?

Example without `calculate_all`:

```
User.group_by_day(:created_at, format: "%d.%m").count

=> {"16.07"=>147, "17.07"=>1049, "18.07"=>885, "19.07"=>957, "20.07"=>1195, "21.07"=>1123, "22.07"=>1249, "23.07"=>304}
```

But with `calculate_all`:

```
User.group_by_day(:created_at, format: "%d.%m").calculate_all(:count)

=> {2018-07-15 22:00:00 UTC=>146, 2018-07-16 22:00:00 UTC=>1049,  2018-07-17 22:00:00 UTC=>885, 2018-07-18 22:00:00 UTC=>957, 2018-07-19 22:00:00 UTC=>1195, 2018-07-20 22:00:00 UTC=>1123, 2018-07-21 22:00:00 UTC=>1249, 2018-07-22 22:00:00 UTC=>304}
```

**Comment by haffla** [comment]
Sorry for opening this issue, it seems the errors is somewhere in my own code. Cheers!

**Comment by haffla** [comment]
The issue is resolved when I downgrade to `groupdate` < 4.

**Comment by codesnik** [comment]
Hi, thanks for using it!
I'm surprised `format` option is working at all, it looks like it wasn't there in groupdate when I made this gem. I definitely should check what's new in groupdate 4, but I'm not sure I'll be able to fix it without some ugly hacks or copypasting of groupdate formatting code, though. 

meanwhile

```ruby
User.group_by_day(:created_at).calculate_all(:count).transform_keys {|d| d.strftime "%d.%m" }
```

or (providing you defined :short_date as "%d.%m" in `config/locales/*.yml`

```ruby
User.group_by_day(:created_at).calculate_all(:count).transform_keys {|d| d.to_s :short_date }
```

should work.

**Comment by haffla** [comment]
The format option is in `groupdate` since version 2. 
I've been looking through `groupdate` source code and it seems that the bump from 3 to 4 was really major. Before there was a lot of hacking using `method_missing` and `alias_method_chain`. 

Now I believe the formatting of the hash keys is done by overwriting the `calculate` method (which is called by `sum`, `count`, `average` etc) from `ActiveRecord::Calculations`. So when you call `calculate_all` you don't call any of these methods and transformation is not performed. 

Thanks for the tip about defining the date formats in `yml` files. I think that's the way to go in my case.
